global:
  environment:
    name: dev

reusable-api-chart:
  ingress:
    internal:
      domainName: map-onsite-apis.aks-ur-dev-internal.8451.cloud

  hpa:
    minReplicas: 1
    maxReplicas: 2

  externalSecrets:
    enabled: true
    azureKeyVaults:
      primary:
        vaultUrl: https://kv-8451-map-dev.vault.azure.net/
      secondary:
        vaultUrl: https://kv-8451-onsite3p-dev.vault.azure.net/

  extraEnv:
    - name: "ENV"
      value: "dev"
    - name: "REDIS_HOST"
      value: "map-redis-cache-dev.redis.cache.windows.net"
    - name: "REDIS_PORT"
      value: "6380"
    - name: "REDIS_DB"
      value: "1"
    - name: "REDIS_SSL"
      value: "true"
    - name: "REDIS_SOCKET_TIMEOUT"
      value: "10"
    - name: "REDIS_SOCKET_CONNECT_TIMEOUT"
      value: "10"
